### ISSUE TITLE
Behavior for non-breaking space

### ISSUE THREAD

**Issue by Comandeer** [mlewand/benderjs-yui-beautified#1]
1. Prepare test with assertion:

```javascript
assert.beautified.html( '<div>aaaa</div><div>b</div>', '<div>aaaa</div> <div>b</div>' );
```

(note that in the second code there is a non-breaking space between `</div>` and `<div>`).
2. Run test.

Currently the test is failing, but I'm not sure if such space shouldn't be treated just like normal whitespace.

**Comment by mlewand** [comment]
Non-breaking spaces actually matters, so it make sense for it to fail upon nbsp's. It's better to catch it in tests, than have a lovely evening on debugging what's going on :D
